# Generated by Django 3.0.7 on 2020-06-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devopsuser',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
